export const MENSAGENS_PADRAO = {
    CAD0001: 'CONTA NÃO FOI CRIADA. PROPONENTE NÃO ELEGÍVEL PARA ABERTURA DE CONTA. SCORE MUITO BAIXO.',
    CAD0002: 'PROPONENTE ELEGÍVEL.',
    CAD0003: 'CONTA NÃO FOI CRIADA. PROPONENTE JÁ POSSUI CONTA.',
    CAD0004: 'CPF JÁ POSSUI CADASTRO NO BANCO'
};
